name: flutter_chatting
description: flutter chatting
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_bloc:
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  shared_preferences: ^0.5.3+4
  meta: ^1.1.8
  equatable: 1.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
